### ISSUE TITLE
Popular files page TODO list

### ISSUE THREAD

**Issue by jmervine** [MaxCDN/bootstrap-cdn#613]
- [x] Add unit tests for `lib/maxcdn.js`.
- [x] Add unit tests for `lib/store.js`.
- [x] Add unit tests for `/popular/` endpoint.
- [ ] Add functional tests.
- [x] Verify cache failover.
- [x] Remove decimal from hits number. (see: http://numeraljs.com/)
- [x] Transform bandwidth numbers to "TB" when applicable. (see: http://numeraljs.com/)
- [x] Fix jquery.tablesorter plugin.
- [ ] Consider using tabs for individual products (i.e. Bootstrap, Font Awesome, Bootswatch, Other)
- [ ] Consider adding a plot graph of `bootstrap/*/css/bootstrap.min.css` hits and bandwidth over time.

cc: @jdorfman

**Comment by jdorfman** [comment]
:+1:
